#!/usr/bin/python3

import boto3
import botocore
import os

awsRegion = os.environ['AWS_DEFAULT_REGION']

ec2Client = boto3.client('ec2', region_name=awsRegion)

tags = ec2Client.describe_tags()

for tag in tags['Tags']:
    if tag['Key'] == '<tagKey>' and tag['ResourceType'] == 'instance': # Replace '<tagKey>' with name of tag key.
        response = ec2Client.delete_tags(
                Resources = [
                    tag['ResourceId'],
                    ],
                Tags=[
                    {
                        'Key': '<tagKey>', # Replace '<tagKey>' with name of tag key.
                        'Value': '<tagValue>' # Replace '<tagValue>' with name of tag value.
                        },
                    ]
                )
