#!/usr/bin/python3

import boto3
import botocore
import os

awsRegion = os.environ['AWS_DEFAULT_REGION']

ec2Client = boto3.client('ec2', region_name=awsRegion)
'''
instances = ec2Client.describe_instances()

for reservation in instances['Reservations']:
    reservations = reservation['Instances']
    for instanceId in reservations:
        instanceIds = instanceId['InstanceId']
        #print(instanceIds)


for instance in instanceIds:
    response = ec2Client.describe_tags(
            Filters=[
                {
                    'Name': 'resource-id',
                    'Values': [
                        instance,
                        ]
                    }
                ]
            )
    print(response)
'''

tags = ec2Client.describe_tags()

for tag in tags['Tags']:
    if tag['Key'] == 'mission:managed-cloud:backup:weekly' and tag['ResourceType'] == 'instance':
        response = ec2Client.delete_tags(
                Resources = [
                    tag['ResourceId'],
                    ],
                Tags=[
                    {
                        'Key': 'mission:managed-cloud:backup:weekly',
                        'Value': '28days'
                        },
                    ]
                )
