#!/usr/bin/python3

import boto3
import botocore
import os

awsRegion = os.environ['AWS_DEFAULT_REGION']

ec2Client = boto3.client('ec2', region_name=awsRegion)

tags = ec2Client.describe_tags()

for tag in tags['Tags']:
    if tag['Key'] == 'mission:managed-cloud:backup:weekly' and tag['ResourceType'] == 'instance':
        response = ec2Client.delete_tags(
                Resources = [
                    tag['ResourceId'],
                    ],
                Tags=[
                    {
                        'Key': 'mission:managed-cloud:backup:weekly',
                        'Value': '28days'
                        },
                    ]
                )
